from reportlab.lib import colors
from reportlab.lib.pagesizes import letter
from reportlab.platypus import SimpleDocTemplate, Paragraph, Spacer, Table, TableStyle
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from io import BytesIO
from typing import List, Dict
from datetime import datetime

class ReportGenerator:
    def __init__(self):
        self.styles = getSampleStyleSheet()
        self.title_style = ParagraphStyle(
            'CustomTitle',
            parent=self.styles['Heading1'],
            fontSize=24,
            spaceAfter=30,
            alignment=1 # Center
        )
        self.heading_style = self.styles['Heading2']
        self.normal_style = self.styles['Normal']

    def generate_incident_report(self, attacker_ip: str, logs: List[dict], stats: dict) -> bytes:
        buffer = BytesIO()
        doc = SimpleDocTemplate(buffer, pagesize=letter)
        story = []

        # Title
        story.append(Paragraph("CHAMELEON SYSTEM Security Incident Report", self.title_style))
        story.append(Spacer(1, 12))

        # Metadata
        report_id = f"RPT-{int(datetime.utcnow().timestamp())}"
        meta_data = [
            ["Report Date:", datetime.utcnow().strftime("%Y-%m-%d %H:%M:%S UTC")],
            ["Report ID:", report_id],
            ["Attacker IP:", attacker_ip],
            ["Total Incidents:", str(len(logs))]
        ]
        meta_table = Table(meta_data, colWidths=[2*inch, 4*inch])
        meta_table.setStyle(TableStyle([
            ('FONTNAME', (0,0), (0,-1), 'Helvetica-Bold'),
            ('ALIGN', (0,0), (-1,-1), 'LEFT'),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
        ]))
        story.append(meta_table)
        story.append(Spacer(1, 20))

        # Executive Summary
        story.append(Paragraph("Executive Summary", self.heading_style))
        summary_text = (
            f"This report details suspicious activities detected from IP address {attacker_ip}. "
            f"The Chameleon Adaptive Deception System has intercepted {len(logs)} attempts. "
            "The system has applied adaptive countermeasures including artificial delays and deceptive responses."
        )
        story.append(Paragraph(summary_text, self.normal_style))
        story.append(Spacer(1, 20))

        # Attack Distribution
        story.append(Paragraph("Attack Distribution", self.heading_style))
        dist_data = [["Attack Type", "Count"]]
        
        # Calculate distribution for this specific IP
        type_counts = {}
        for log in logs:
            a_type = log.get("classification", {}).get("attack_type", "UNKNOWN")
            type_counts[a_type] = type_counts.get(a_type, 0) + 1
            
        for a_type, count in type_counts.items():
            dist_data.append([a_type, str(count)])
            
        dist_table = Table(dist_data, colWidths=[3*inch, 2*inch])
        dist_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
            ('TEXTCOLOR', (0,0), (-1,0), colors.black),
            ('ALIGN', (0,0), (-1,-1), 'CENTER'),
            ('FONTNAME', (0,0), (-1,0), 'Helvetica-Bold'),
            ('GRID', (0,0), (-1,-1), 1, colors.black)
        ]))
        story.append(dist_table)
        story.append(Spacer(1, 20))

        # Detailed Logs (Top 20)
        story.append(Paragraph("Recent Incidents (Last 20)", self.heading_style))
        log_data = [["Time", "Type", "Input (Truncated)", "Response"]]
        
        for log in logs[:20]:
            timestamp = log.get("timestamp")
            if isinstance(timestamp, datetime):
                ts_str = timestamp.strftime("%H:%M:%S")
            else:
                ts_str = str(timestamp)
                
            a_type = log.get("classification", {}).get("attack_type", "N/A")
            raw_input = log.get("raw_input", "")
            if len(raw_input) > 30:
                raw_input = raw_input[:27] + "..."
            
            response = log.get("deception_response", {}).get("message", "")
            if len(response) > 30:
                response = response[:27] + "..."
                
            log_data.append([ts_str, a_type, raw_input, response])
            
        log_table = Table(log_data, colWidths=[1.2*inch, 1.2*inch, 2*inch, 2*inch])
        log_table.setStyle(TableStyle([
            ('BACKGROUND', (0,0), (-1,0), colors.lightgrey),
            ('FONTSIZE', (0,0), (-1,-1), 8),
            ('GRID', (0,0), (-1,-1), 0.5, colors.grey)
        ]))
        story.append(log_table)
        story.append(Spacer(1, 30))

        # Footer
        footer_text = "Generated by Chameleon System. All logs are cryptographically signed and immutable."
        story.append(Paragraph(footer_text, ParagraphStyle('Footer', parent=self.normal_style, fontSize=8, textColor=colors.grey)))

        doc.build(story)
        return buffer.getvalue()

report_generator = ReportGenerator()
